### ISSUE TITLE
[FR][EPIC]  Interact with the VNC server (textbased)

### ISSUE THREAD

**Issue by ByteOtter** [os-autoinst/isotest-ng#4]
### openQA Version

n/A

### Impacted library

isototest

### Proposal

# What?

The first thing we need to be able to do is writing to the console of our VNC server.

This includes sending text, handling command sequences and special characters, and moving the text courser.

To achieve this, we can use the [`vnc-rs`](https://github.com/HsuJv/vnc-rs) crate with its `X11Events` to create events like key presses on our server.
According to the [RFC linked in the documentation](https://www.rfc-editor.org/rfc/rfc6143.html#section-7.5.4) and manual testing, these events are working, even if the server does not have an x-server running.

# Resources
- [`vnc-rs`](https://github.com/HsuJv/vnc-rs)
- https://www.rfc-editor.org/rfc/rfc6143.html#section-7.5.4

# Steps
- [x] Send raw text input
- [x] Handle special characters like Linebreaks, etc.
- [x] Handle Command Sequences

**Comment by ByteOtter** [comment]
Fixed by #8
